## Technique: Suffix-Based Feature Grouping

Suffix-Based Feature Grouping is an EDA and feature engineering technique used to organize columns that share the same suffix into separate groups or DataFrames. This is particularly useful when column names follow a naming convention, such as measurements from different sensors, time points, or statistics.

Instead of manually selecting columns, we can automatically group them based on their suffix.

In [1]:
import pandas as pd

df = pd.DataFrame({
    "temp_A": [100, 102, 98],
    "pressure_A": [40, 42, 39],
    "speed_A": [10, 11, 12],

    "temp_B": [95, 97, 96],
    "pressure_B": [35, 36, 37],
    "speed_B": [8, 9, 10],

    "Defective_flag": [0, 1, 0]
})
df

   temp_A  pressure_A  speed_A  temp_B  pressure_B  speed_B  Defective_flag
0     100          40       10      95          35        8               0
1     102          42       11      97          36        9               1
2      98          39       12      96          37       10               0

In [3]:
from collections import defaultdict
suffix_groups=defaultdict(list)

for col in df.columns:
    if "_" in col:
        suffix=col.split('_')[-1]
        suffix_groups[suffix].append(col)
suffix_groups

defaultdict(list,
            {'A': ['temp_A', 'pressure_A', 'speed_A'],
             'B': ['temp_B', 'pressure_B', 'speed_B'],
             'flag': ['Defective_flag']})

In [4]:
df_suffix={}


for suffix,cols in suffix_groups.items():
    df_suffix[suffix]=df[cols]

df_suffix

{'A':    temp_A  pressure_A  speed_A
 0     100          40       10
 1     102          42       11
 2      98          39       12,
 'B':    temp_B  pressure_B  speed_B
 0      95          35        8
 1      97          36        9
 2      96          37       10,
 'flag':    Defective_flag
 0               0
 1               1
 2               0}

In [6]:
df_suffix['A']

   temp_A  pressure_A  speed_A
0     100          40       10
1     102          42       11
2      98          39       12

In [7]:
df_suffix['B']

   temp_B  pressure_B  speed_B
0      95          35        8
1      97          36        9
2      96          37       10

## Skewness Analysis:
Measure whether a numerical feature is symmetric.

Interpretation

0      Symmetric

,>0     Right-skewed

<0   Left-skewed

Applications

Decide log transformation.

Feature engineering.

In [2]:
df.skew(numeric_only=True)

temp_A            0.000000
pressure_A        0.935220
speed_A           0.000000
temp_B            0.000000
pressure_B        0.000000
speed_B           0.000000
Defective_flag    1.732051
dtype: float64

## Check Memory Usage by the dataset

In [3]:
df.memory_usage(deep=True)

Index             132
temp_A             24
pressure_A         24
speed_A            24
temp_B             24
pressure_B         24
speed_B            24
Defective_flag     24
dtype: int64

In [4]:
df.info(memory_usage=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   temp_A          3 non-null      int64
 1   pressure_A      3 non-null      int64
 2   speed_A         3 non-null      int64
 3   temp_B          3 non-null      int64
 4   pressure_B      3 non-null      int64
 5   speed_B         3 non-null      int64
 6   Defective_flag  3 non-null      int64
dtypes: int64(7)
memory usage: 300.0 bytes

Applications

Optimize large datasets.

Convert object → category.

## Cumulative Distribution Analysis
Purpose

Study cumulative frequencies


Applications

Distribution analysis.

Threshold selection.

In [8]:
df['temp_A'].value_counts().sort_index().cumsum()

temp_A
98     1
100    2
102    3
Name: count, dtype: int64